config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html  
  # We can do this either with get or with resources
  # get 'users', to: 'users#index'
  # get 'users/:id', to: 'users#show'
  # get 'users/:user_id/posts', to: 'posts#index'
  # get 'users/:user_id/posts/:id', to: 'posts#show'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  root 'users#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    can :read, Post
    return unless user.present?

    can :destroy, [Post, Comment], user_id: user.id
    return unless user.admin?

    can :create, [Post, Comment]
    can :destroy, [Post, Comment]
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
  after_save :comments_counter

  def comments_counter
    post = Post.find(post_id)
    post.increment!(:commentsCounter)
  end

  def find_author
    User.find(author_id).name
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, foreign_key: 'post_id'
  after_save :likes_counter

  def likes_counter
    post = Post.find(post_id)
    post.increment!(:likesCounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :commentsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true
  validates :likesCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  after_save :update_counter

  def update_counter
    user = User.find(author_id)
    user.increment!(:postsCounter)
  end

  def update_comments_counter
    self.commentsCounter = Comment.where(post_id: id).count
    save
  end

  def update_likes_counter
    self.likesCounter = Like.where(post_id: id).count
    save
  end

  def most_recent_comments
    Comment.where(post_id: id).last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  enum role: %i[user admin]
  after_initialize :set_default_role, if: :new_record?

  validates :name, presence: true
  validates :postsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  def most_recent_posts
    Post.where(author_id: id).last(3)
  end

  def set_default_role
    self.role ||= :user
  end

  def update_posts_counter
    self.postsCounter = Post.where(author_id: id).count
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :surname, :email, :password, :current_password)}
  end

  #def current_user
    #User.first
    # This could serve when we implement authentication
    # @current_user ||= User.find(session[:user_id]) if session[:user_id]
  #end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post

  def new
    @comment = Comment.new
  end

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author_id = @user.id

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Successfully added a Comment!'
    else
      flash.now[:notice] = 'Comment could not be created'
      render 'posts/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to root_path, notice: 'Comment Deleted!'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post, :find_user

  def create
    @like = @post.likes.new(author: @user)
    if @like.save
      redirect_to user_post_path(@user, @post), notice: 'Successfully added a Like!'
    else
      flash.now[:notice] = 'Failed to add Like.'
      render 'posts/show'
    end
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_user
    @user = current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: @user.id)
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.author_id)
    @comments = Comment.where(post_id: @post.id)
    @comment = Comment.all.where("post_id = #{params[:id]}, user_id = #{params[:user_id]}")
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(params[:user_id])

    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_path(@user), notice: 'Successfully added a Post!'
    else
      flash.now[:notice] = 'Failed to create a Post.'
      render 'users/show'
    end
  end
  
  def destroy
    post = Post.find(params[:post_id])
    post.destroy

    redirect_to user_path, notice: 'Post is deleted!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(author_id: @user.id).order(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments_component.html.erb
<h2>Post a comment</h2>
<%= form_with model: [@user, @post, @post.comments.create] do |form| %>
  <%= form.text_area :text, placeholder: 'Your comment here' %><br><br>
  <%= form.submit 'Post your Comment ' %><br><br>
<% end %>

app/views/comments/_form_component.html.erb
<h2 class="mb-2vh">Write a new comment:</h2>
<%= form_with model: [@user, @post, @post.comments.build] do |form| %>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit "Post a Comment" %>
  </p>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoR Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_user %>
      <p>Hello <%= current_user.name %> </p>
      <p>You are logged as: <%= current_user.role %>  </p>
      <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/custom/_comment_component.html.erb
<p class="comment-paragraph"><%= comment.find_author %>: <%= comment.text %></p>
<% if can? :destroy, comment %>
  <%= button_to "Delete Comment", user_post_comment_path(user_id: current_user.id, post_id: @post.id, id:comment.id), method: :delete %>
<% end %>

app/views/layouts/custom/_post_component.html.erb
<%= link_to user_post_path(post.author, post), class:"post-component" do %>
  <div class="post-div">
    <h3><%= post.title %></h3>
    <p><%= post.text %></p>
    <p class="post-right">Comments: 
        <% if post.commentsCounter.nil? %>
            0
        <% else %>
            <%= post.commentsCounter %>
        <% end %>
    , Likes: 
        <% if post.likesCounter.nil? %>
            0
        <% else %>
            <%= post.likesCounter %>
        <% end %>
    </p>
  </div>
  <% if can? :destroy, post %>
    <%= button_to "Delete Post", user_post_path(user_id: current_user.id, post_id: post.id), method: :delete %>
  <% end %>
<% end %>

app/views/layouts/custom/_user_component.html.erb
<div class="user-div">
  <img src="<%= user.photo %>" class="user-img" alt="profile picture of <%= user.name %>"></img>

  <%= link_to user_path(user), class:"user-link" do %>
    <div class="usr-inf">
      <h3 class="user-name"><%= user.name %></h3>
      <% if user.postsCounter.nil? %>
        <p class="posts">Number of posts: 0</p>
      <% else %>
        <p class="posts">Number of posts: <%= user.postsCounter %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/likes/_likes_component.html.erb
<%= form_with model: [@user, @post, @post.likes.create] do |form| %>
  <%= form.submit '+ Like' %><br><br>
<% end %>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/posts/_form_component.html.erb
<h2 class="mb-2vh">Write a new post:</h2>
<%= form_with model: [ current_user, current_user.posts.build] do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
    <p>
      <%= form.submit "Add Post" %>
    </p>
<% end %>

app/views/posts/index.html.erb
<%= render 'layouts/custom/user_component', user: @user %>
<% @posts.each do |post| %>
  <%= render 'layouts/custom/post_component', post: post %>

  <div>
    <% if post.most_recent_comments.empty? %>
      <p>No comments have been writted to this post yet.</p>
    <% else %>
      <div class="comment-container">
        <% post.most_recent_comments.each do |comment| %>
          <%= render 'layouts/custom/comment_component', comment: comment %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

  <div style="display: flex; justify-content: center;">
    <a href="/users/<%= @user.id %>/posts" class="button">
      Pagination
    </a>
  </div>

<%= render "form_component" %>

app/views/posts/show.html.erb
<h1>Post</h1>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
  <% end -%>
<div class="post-div">
  <h3 class="post-title">
    <%= @post.title %>
  </h3>
    <p class="post-upper-right">Comments: 
      <% if @post.commentsCounter.nil? %>
          0
      <% else %>
          <%= @post.commentsCounter %>
      <% end %>
      , Likes: 
      <% if @post.likesCounter.nil? %>
          0
      <% else %>
          <%= @post.likesCounter %>
      <% end %>
    </p>
  <p><%= @post.text %></p>
</div>
<% if @comments.empty? %>
  <p>No comments have been writted to this post yet.</p>
<% else %>
  <div class="comment-container">
    <% @comments.each do |comment| %>
      <%= render 'layouts/custom/comment_component', comment: comment %>
    <% end %>
  </div>
<% end %>

<%= render 'comments/comments_component' %>
<%= render 'likes/likes_component' %>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
    <li>
      <%= render 'layouts/custom/user_component', user: user %> <br>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div>
  <%= render 'layouts/custom/user_component', user: @user %>

  <div class="user-bio">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>

  <% @user.most_recent_posts.each do |post| %>
    <%= render 'layouts/custom/post_component', post: post %>
  <% end %>
  <!--button><%= link_to 'See all posts', user_posts_path(@user) %></#button-->
  <div style="display: flex; justify-content: center;">
    <a href="/users/<%= @user.id %>/posts" class="button">
      See all <%= @user.name %>'s posts
    </a>
  </div>
</div>